"""FastAPI application entry. Generated by simplicio scratch (py-fastapi).

The planner is expected to add routers under src/api/ and mount them here.
"""
from fastapi import FastAPI


def create_app() -> FastAPI:
    app = FastAPI(title="{project_name}")

    @app.get("/health")
    async def health() -> dict[str, str]:
        return {"status": "ok"}

    return app


app = create_app()


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)
