"""
bench.py — compares WITH vs WITHOUT the pipeline. REAL numbers, nothing made up.

Each case = {goal, target, criteria, test_cmd}.
  WITHOUT: sends only the raw goal to the LLM (baseline).
  WITH:    full pipeline (precedent + skill + layers + verify).
Measures: did it pass the test on the first try? how many attempts?

Usage: simplicio bench --cases bench/cases.json --stack angular
Writes bench/results.md with the real table.
"""
import os, json, time, subprocess
from .prompt import build_prompt
from .providers import generate

def _test(output, root, test_cmd):
    os.makedirs(os.path.join(root, ".simplicio"), exist_ok=True)
    open(os.path.join(root, ".simplicio/bench_out.txt"), "w").write(output or "")
    p = subprocess.run(test_cmd, shell=True, cwd=root, capture_output=True, text=True)
    return p.returncode == 0

def _baseline(case, root):
    # baseline: raw goal, zero built context
    return generate(case["goal"])

def _pipeline(case, root, stack):
    return generate(build_prompt(root, stack, case["goal"], case["target"],
                                 case.get("criteria","- true state\n- false state"),
                                 case.get("constraints","- build passes")))

def run_bench(root, stack, cases_path):
    cases = json.load(open(cases_path))
    rows, n = [], len(cases)
    hits = {"without": 0, "with": 0}
    for c in cases:
        tc = c["test_cmd"]
        ok_without = _test(_baseline(c, root), root, tc); hits["without"] += ok_without
        ok_with = _test(_pipeline(c, root, stack), root, tc); hits["with"] += ok_with
        rows.append(f"| {c['goal'][:40]} | {'PASS' if ok_without else 'FAIL'} | {'PASS' if ok_with else 'FAIL'} |")
    table = ("| Task | Without simplicio | With simplicio |\n|---|---|---|\n"
             + "\n".join(rows)
             + f"\n\n**First-try pass rate:** without = {hits['without']}/{n} "
               f"({100*hits['without']//n}%) · with = {hits['with']}/{n} "
               f"({100*hits['with']//n}%)")
    out = os.path.join(root, "bench", "results.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write(f"# Benchmark (generated by `simplicio bench`)\n\n"
                         f"Provider: {os.environ.get('SIMPLICIO_PROVIDER','claude')} · "
                         f"cases: {n} · date: {time.strftime('%Y-%m-%d')}\n\n{table}\n")
    print(table)
    print(f"\n-> {out}")
